//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTDHBaiKiemTraGK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NTDHCNTT2Lesson07DbEntities : DbContext
    {
        public NTDHCNTT2Lesson07DbEntities()
            : base("name=NTDHCNTT2Lesson07DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NTDHKhoa> NTDHKhoa { get; set; }
        public virtual DbSet<NTDHSinhVien> NTDHSinhVien { get; set; }
    }
}
