//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTDHBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTDHSinhVien
    {
        public string NTDHMaSV { get; set; }
        public string NTDHHoSV { get; set; }
        public string NTDHTenSV { get; set; }
        public Nullable<System.DateTime> NTDHNgaySinh { get; set; }
        public Nullable<bool> NTDHPhai { get; set; }
        public string NTDHPhone { get; set; }
        public string NTDHEmail { get; set; }
        public string NTDHMaKH { get; set; }
    }
}
