//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTDHBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTDHKhoa
    {
        public string NTDHMaKH { get; set; }
        public string NTDHtenKH { get; set; }
        public Nullable<bool> NTDHTrangThai { get; set; }
    }
}
